updated

diff --git a/bin/install-go b/bin/install-go
--- a/bin/install-go
+++ b/bin/install-go
@@ -1,38 +1,58 @@
 #!/bin/bash
-set -euf -o pipefail
-
 #force run with bash
 if [ -z "$BASH_VERSION" ]; then
   exec bash "$0" "$@"
   return
 fi
-
-#create local scope
+#run without sudo, then with, if needed
+function psudo() {
+  OUT=$(bash -c "exec $*" 2>&1)
+  STATUS=$?
+  if [ $STATUS -eq 0 ]; then
+    return 0
+  fi
+  if [[ $OUT =~ "Permission denied" ]]; then
+    echo "attempting 'sudo $@'"
+    sudo bash -c "exec $*"
+  else
+    echo "command '$@' failed"
+    exit 1
+  fi
+}
+#install go
 function install {
-  # test permissions
-  mkdir -p /usr/local/go
   # detect latest version
   echo "Discovering latest version of Go..."
-  typeset VER=$(curl -s https://go.dev/dl/ | grep -m 1 -o 'go1\(\.[0-9]\+\)\+' | head -n1)
+  declare VER=$(curl -s https://go.dev/dl/ | grep -m 1 -o 'go1\(\.[0-9]\+\)\+' | head -n1)
   echo "Detected latest: $VER"
-  # TODO compare latest to current installed
+  # detect if already have latest
+  if which go >/dev/null; then
+    if go version | grep -q "$VER "; then
+      echo "$VER already installed"
+      return
+    fi
+  fi
   # wipe old version
-  rm -rf /usr/local/go
+  psudo rm -rf /usr/local/go
   # detect os/arch
-  typeset OS=$(uname -s | tr 'A-Z' 'a-z')
+  declare OS=$(uname -s | tr 'A-Z' 'a-z')
   if uname -m | grep arm64 >/dev/null; then
-    typeset ARCH=arm64
+    declare ARCH=arm64
   elif uname -m | grep arm >/dev/null; then
-    typeset ARCH=armv6l
+    declare ARCH=armv6l
   elif uname -m | grep 64 >/dev/null; then
-    typeset ARCH=amd64
+    declare ARCH=amd64
   else
-    typeset ARCH=386
+    declare ARCH=386
   fi
   # download
-  typeset FILE=$VER.$OS-$ARCH.tar.gz
-  echo "Installing '$FILE' into /usr/local/go"
-  curl -# -L "https:/go.dev/dl/$FILE" | tar -C /usr/local -zxf -
+  declare FILE="$VER.$OS-$ARCH.tar.gz"
+  declare TMP_DIR=$(mktemp -d -t go)
+  echo "Downloading '$FILE' into $TMP_DIR"
+  curl -# -L "https:/go.dev/dl/$FILE" | tar -C $TMP_DIR -zxf -
+  declare GO_DIR="$TMP_DIR/go"
+  echo "Go has been downloaded. Installing into /usr/local/go"
+  psudo mv $GO_DIR /usr/local/go
   echo "Go has been installed. Add /usr/local/go/bin to your PATH."
 }
 install
